apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary-demo
  namespace: argocd
spec:
  project: default
  source:
    path: rollouts-demo/canary/
    repoURL: 'https://github.com/HardwareAndro/argo-cd-manifests.git'
    targetRevision: main
  destination:
    namespace: canary
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2